version: '3.8'

services:
  python-llm:
    build: 
      context: ./python-llm
      dockerfile: Dockerfile
    volumes:
      - ./python-llm:/app
    environment:
      - PYTHONUNBUFFERED=1

  express-api:
    build: 
      context: ./express-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - python-llm
    volumes:
      - ./express-api:/app
    environment:
      - NODE_ENV=production
    env_file:
      - ./express-api/.env

volumes:
  mongodb-data:
